In [32]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure

In [35]:
def siftTrack(trainImg,trainKP,trainDesc,QueryImgBGR):
    MIN_MATCH_COUNT=10

    detector=cv2.xfeatures2d.SIFT_create()

    FLANN_INDEX_KDITREE=0
    flannParam=dict(algorithm=FLANN_INDEX_KDITREE,tree=5)
    searchParam = dict(checks=50)
    flann=cv2.FlannBasedMatcher(flannParam,searchParam)

    #trainImg=cv2.imread("demo0.png",0)
    #trainKP,trainDesc=detector.detectAndCompute(trainImg,None)

    #cam=cv2.VideoCapture(0)
    #while True:
    #ret, QueryImgBGR=cam.read()
    
    QueryImg=cv2.cvtColor(QueryImgBGR,cv2.COLOR_BGR2GRAY)
    queryKP,queryDesc=detector.detectAndCompute(QueryImg,None)
    matches=flann.knnMatch(queryDesc,trainDesc,k=2)

    goodMatch=[]
    for m,n in matches:
        if(m.distance < 0.7*n.distance):
            goodMatch.append(m)
    if(len(goodMatch) > MIN_MATCH_COUNT):
        tp=[]
        qp=[]
        for m in goodMatch:
            tp.append(trainKP[m.trainIdx].pt)
            qp.append(queryKP[m.queryIdx].pt)
        tp,qp=np.float32((tp,qp))
        H,status=cv2.findHomography(tp,qp,cv2.RANSAC,3.0)
        print(H)
        
        #h,w=trainImg.shape
        #trainBorder=np.float32([[[0,0],[0,h-1],[w-1,h-1],[w-1,0]]])
        #queryBorder=cv2.perspectiveTransform(trainBorder,H)
        #cv2.polylines(QueryImgBGR,[np.int32(queryBorder)],True,(0,255,0),5)
        return 1
        #print(queryBorder)
    else:
        #print("Not Enough match found")
        return -1



In [ ]:
cam = cv2.VideoCapture(0)
img1 = cv2.imread("demo0.png")
sift = cv2.xfeatures2d.SIFT_create()
kp1, des1 = sift.detectAndCompute(img1,None)
while True:
    ret, img2=cam.read()
    checker = siftTrack(img1,kp1,des1,img2)
    if checker != -1:
        #img2 = cv2.polylines(img2,[np.int32(dst)],True,255,3, cv2.LINE_AA)
        print("YES")
    else:
        print("NO")
    keypressed = cv2.waitKey(5)
    if keypressed == 27:
        break
    cv2.imshow('mask',img2)
    
cam.release()
cv2.destroyAllWindows()

NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
None
YES
NO
NO
NO
NO
NO
NO
NO
None
YES
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
[[ -8.45813788e-02   4.33605976e-01  -2.24277816e+02]
 [  5.95582509e-02  -6.51952762e-01   1.59100038e+01]
 [ -2.73104143e-03  -5.71529279e-03   1.00000000e+00]]
YES
NO
NO
NO
NO
NO
NO
NO
None
YES
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
None
YES
NO
NO
NO
NO
NO
NO
[[ -6.71050883e-01  -2.51594122e-01   4.09289536e+02]
 [ -4.91960837e-02  -2.58849602e-01   1.17588339e+02]
 [ -1.32283497e-03  -1.01980673e-03   1.00000000e+00]]
YES
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
[[ -4.24336827e-01  -3.63975025e-01   1.32928311e+02]
 [ -1.02255075e-01  -9.12889960e-02   3.05897215e+01]
 [ -2.67690449e-03  -2.86198941e-03   1.00000000e+00]]
YES
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
[[  1.84337905e-01  -4.32022751e-02   3.083

[[  2.27230528e-01  -8.12014140e-03   3.71974163e+02]
 [ -2.76057008e-02   2.67356297e-01   1.31953276e+02]
 [ -1.24257921e-04  -1.29959679e-05   1.00000000e+00]]
YES
[[  1.96940343e-01   1.46681402e-03   3.69956545e+02]
 [ -4.03814836e-02   2.74331383e-01   1.31465715e+02]
 [ -1.83989207e-04   1.59725278e-05   1.00000000e+00]]
YES
[[  1.88697029e-01  -4.48917601e-02   3.71426027e+02]
 [ -4.24413350e-02   2.50325604e-01   1.32836103e+02]
 [ -1.79815028e-04  -8.35093654e-05   1.00000000e+00]]
YES
[[  1.84374899e-01  -2.64541707e-03   3.67074943e+02]
 [ -4.60423936e-02   2.71739377e-01   1.32709048e+02]
 [ -2.03500165e-04   5.61909648e-06   1.00000000e+00]]
YES
[[  1.93982326e-01   1.33452329e-02   3.64700498e+02]
 [ -4.48970084e-02   2.82196812e-01   1.32640405e+02]
 [ -1.94543977e-04   3.56380631e-05   1.00000000e+00]]
YES
[[  1.88577856e-01   3.22610395e-02   3.63690227e+02]
 [ -5.05142487e-02   2.95031955e-01   1.32748623e+02]
 [ -2.14752719e-04   8.29155672e-05   1.00000000e+00]]
YE